# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\cisco\Desktop\Final project\CountriesoftheWorld.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ListWidget_Countries = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidget_Countries.setGeometry(QtCore.QRect(10, 40, 221, 461))
        self.ListWidget_Countries.setObjectName("ListWidget_Countries")
        self.label_ChooseCountry = QtWidgets.QLabel(self.centralwidget)
        self.label_ChooseCountry.setGeometry(QtCore.QRect(10, 20, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ChooseCountry.setFont(font)
        self.label_ChooseCountry.setObjectName("label_ChooseCountry")
        self.Box_SqUnits = QtWidgets.QComboBox(self.centralwidget)
        self.Box_SqUnits.setGeometry(QtCore.QRect(330, 330, 111, 21))
        self.Box_SqUnits.setObjectName("Box_SqUnits")
        self.Box_SqUnits.addItem("")
        self.Box_SqUnits.addItem("")
        self.Box_PopulationDensity = QtWidgets.QGroupBox(self.centralwidget)
        self.Box_PopulationDensity.setGeometry(QtCore.QRect(250, 360, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Box_PopulationDensity.setFont(font)
        self.Box_PopulationDensity.setObjectName("Box_PopulationDensity")
        self.RadioButton_SqKM = QtWidgets.QRadioButton(self.Box_PopulationDensity)
        self.RadioButton_SqKM.setGeometry(QtCore.QRect(20, 50, 111, 17))
        self.RadioButton_SqKM.setObjectName("RadioButton_SqKM")
        self.RadioButton_SqMile = QtWidgets.QRadioButton(self.Box_PopulationDensity)
        self.RadioButton_SqMile.setGeometry(QtCore.QRect(20, 30, 121, 17))
        self.RadioButton_SqMile.setChecked(True)
        self.RadioButton_SqMile.setObjectName("RadioButton_SqMile")
        self.Label_PopulationDensity = QtWidgets.QLabel(self.Box_PopulationDensity)
        self.Label_PopulationDensity.setGeometry(QtCore.QRect(240, 50, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_PopulationDensity.setFont(font)
        self.Label_PopulationDensity.setText("")
        self.Label_PopulationDensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_PopulationDensity.setObjectName("Label_PopulationDensity")
        self.Label_CountryName = QtWidgets.QLabel(self.centralwidget)
        self.Label_CountryName.setGeometry(QtCore.QRect(250, 40, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label_CountryName.setFont(font)
        self.Label_CountryName.setText("")
        self.Label_CountryName.setObjectName("Label_CountryName")
        self.Label_Population = QtWidgets.QLabel(self.centralwidget)
        self.Label_Population.setGeometry(QtCore.QRect(250, 240, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Population.setFont(font)
        self.Label_Population.setObjectName("Label_Population")
        self.LineEdit_Population = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_Population.setGeometry(QtCore.QRect(330, 240, 251, 20))
        self.LineEdit_Population.setObjectName("LineEdit_Population")
        self.Button_UpdatePopulation = QtWidgets.QPushButton(self.centralwidget)
        self.Button_UpdatePopulation.setGeometry(QtCore.QRect(470, 270, 111, 23))
        self.Button_UpdatePopulation.setObjectName("Button_UpdatePopulation")
        self.Label_AreaIn = QtWidgets.QLabel(self.centralwidget)
        self.Label_AreaIn.setGeometry(QtCore.QRect(250, 330, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_AreaIn.setFont(font)
        self.Label_AreaIn.setObjectName("Label_AreaIn")
        self.Label_TotalArea = QtWidgets.QLabel(self.centralwidget)
        self.Label_TotalArea.setGeometry(QtCore.QRect(460, 320, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_TotalArea.setFont(font)
        self.Label_TotalArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_TotalArea.setText("")
        self.Label_TotalArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_TotalArea.setObjectName("Label_TotalArea")
        self.Label_PercentPop = QtWidgets.QLabel(self.centralwidget)
        self.Label_PercentPop.setGeometry(QtCore.QRect(250, 470, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label_PercentPop.setFont(font)
        self.Label_PercentPop.setObjectName("Label_PercentPop")
        self.Label_PopulationPercentage = QtWidgets.QLabel(self.centralwidget)
        self.Label_PopulationPercentage.setGeometry(QtCore.QRect(470, 470, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_PopulationPercentage.setFont(font)
        self.Label_PopulationPercentage.setText("")
        self.Label_PopulationPercentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_PopulationPercentage.setObjectName("Label_PopulationPercentage")
        self.Label_CountryFlag = QtWidgets.QLabel(self.centralwidget)
        self.Label_CountryFlag.setGeometry(QtCore.QRect(310, 70, 241, 131))
        self.Label_CountryFlag.setText("")
        self.Label_CountryFlag.setObjectName("Label_CountryFlag")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Action_LoadCountries = QtWidgets.QAction(MainWindow)
        self.Action_LoadCountries.setObjectName("Action_LoadCountries")
        self.Action_SaveFile = QtWidgets.QAction(MainWindow)
        self.Action_SaveFile.setObjectName("Action_SaveFile")
        self.Action_Exit = QtWidgets.QAction(MainWindow)
        self.Action_Exit.setObjectName("Action_Exit")
        self.menuFile.addAction(self.Action_LoadCountries)
        self.menuFile.addAction(self.Action_SaveFile)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Action_Exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_ChooseCountry.setText(_translate("MainWindow", "Choose a country from the list:"))
        self.Box_SqUnits.setItemText(0, _translate("MainWindow", "Sq. Miles"))
        self.Box_SqUnits.setItemText(1, _translate("MainWindow", "Sq. KM"))
        self.Box_PopulationDensity.setTitle(_translate("MainWindow", "Population Density"))
        self.RadioButton_SqKM.setText(_translate("MainWindow", "Per Square KM"))
        self.RadioButton_SqMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.Label_Population.setText(_translate("MainWindow", "Population:"))
        self.Button_UpdatePopulation.setText(_translate("MainWindow", "Update Population"))
        self.Label_AreaIn.setText(_translate("MainWindow", "Total Area in"))
        self.Label_PercentPop.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Action_LoadCountries.setText(_translate("MainWindow", "Load Countries"))
        self.Action_SaveFile.setText(_translate("MainWindow", "Save To File"))
        self.Action_Exit.setText(_translate("MainWindow", "Exit"))

